name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
   
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: extractions/setup-just@v2
   
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt
          pip install .
   
      - name: Lint
        run: just lint
   
      - name: Test with pytest
        run: just test
